language: c
sudo: false
cache:
  ccache: true
os:
  - linux
  - osx
env:
  - CC="ccache gcc"
  - CC="ccache g++"
  - CC="ccache clang"
  - CC="ccache clang -fsanitize=address"

# clang++ does not allow c anymore

branches:
  except:
  - /^v?[0-9]+\.[0-9]+/

install:
  - build-tools/autogen.sh

script:
  # skip duplicate compilers and clang++
  - if [ "$TRAVIS_OS_NAME" = "osx" -a "$CC" = "clang" ]; then exit 0; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" -a "$CC" = "g++" ]; then exit 0; fi
  - ./configure
  - make -j4
  - make check

matrix:
  fast_finish: true
