language: c
sudo: false
#cache:
#  ccache: true
os:
  - linux
  - osx
env:
  - XCC="gcc" CONF="--enable-debug --enable-norm-compat" VG=1
  - XCC="cc" CONF="--enable-unsafe"
  - XCC="clang" CONF="--disable-nullslack"
  - XCC="cc" CONF="--disable-extensions"
  - XCC="clang-3.8 -fsanitize=address" CONF="--enable-debug"
# clang++ does not allow c anymore. gcc is duplicate to cc
matrix:
  exclude:
  - env: XCC="gcc"
    env: TRAVIS_OS_NAME=osx
  - env: XCC="cc"
    env: TRAVIS_OS_NAME=osx

branches:
  except:
  - /^v[0-9]+/
  - appveyor

addons:
  apt:
    packages:
    - valgrind
    - clang-3.8

install:
  - build-tools/autogen.sh

script:
  # skip duplicate compilers and overly strict clang++
  - if [ "$TRAVIS_OS_NAME" = "osx" -a "$XCC" = "gcc" ]; then exit 0; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" -a "$XCC" = "clang-3.8 -fsanitize=address" ]; then
      XCC="clang -fsanitize=address";
    fi
  - CC="$XCC" ./configure $CONF
  - make -j4
  - make check || (cat tests/test-suite.log; false)
  - if [ "$VG" = "1" ]; then make check-valgrind && make distcheck ; fi

matrix:
  fast_finish: true
