language: c
sudo: false
#cache:
#  ccache: true
os:
  - linux
  - osx
matrix:
  fast_finish: true
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - valgrind
      env: XCC="gcc" CONF="--enable-debug --enable-norm-compat" VG=1
    - compiler: gcc
      env: XCC="cc" CONF="--enable-unsafe"
    - compiler: clang
      env: XCC="clang" CONF="--disable-nullslack"
    - compiler: gcc
      env: XCC="cc" CONF="--disable-extensions"
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
      env: XCC="clang-3.8 -fsanitize=address" CONF="--enable-debug"
  # clang++ does not allow c anymore. gcc is duplicate to cc
  exclude:
    - env: XCC="gcc" TRAVIS_OS_NAME=osx
    - env: XCC="cc"  TRAVIS_OS_NAME=osx

branches:
  except:
    - /^v[0-9]+/
    - appveyor

install:
  - build-tools/autogen.sh

script:
  # skip duplicate compilers and overly strict clang++
  - if [ "$TRAVIS_OS_NAME" = "osx" -a "$XCC" = "gcc" ]; then exit 0; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" -a "$XCC" = "clang-3.8 -fsanitize=address" ]; then
      XCC="clang -fsanitize=address";
    fi
  - CC="$XCC" ./configure $CONF
  - make -j4
  - make check || (cat tests/test-suite.log; false)
  - if [ "$VG" = "1" ]; then make check-valgrind && make distcheck ; fi
